##https://sauce-demo.myshopify.com/

##Home Page
bnrsimple=//*[@id="logo"]
lnklogin=//a[text()="Log In"]
lnksignup=//a[text()="Sign up"]

##Login Page
lblcustomerlogin=//*[text()="Customer Login"]
edituseremailaddress=//input[@id="customer_email"]
edituserpassord=//input[@id="customer_password"]
btnsigin=//input[@value="Sign In"]


