name: Selenium API Automation

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Verify Java Version
      run: |
        java -version
        mvn -version

    - name: Build and Run Tests
      run: mvn clean test